name = "butaneprotocol/launchpad-validators"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'butaneprotocol/launchpad-validators'"

[repository]
user = "butaneprotocol"
project = "launchpad-validators"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
